### ISSUE TITLE
Beef up null checking

### ISSUE THREAD

**Issue by alis0nc** [alis0nc/bendyboi-tracker#2]
```
Task exception was never retrieved
future: <Task finished coro=<trackBuses() done, defined at ./app.py:99> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "./app.py", line 104, in trackBuses
    tracker.run()
  File "./app.py", line 72, in run
    r = r.get('bustime-response', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

My guess is the API call swallowed an error and returned `None`, then we tried to `get()` from a `None` which obviously we can't do. So yeah not handing the None we might get is a bit of a bad thing.

**Comment by alis0nc** [comment]
closed in e62443a forever ago
