### ISSUE TITLE
Auto announcer breaks occasionally

### ISSUE THREAD

**Issue by ShadowFoxNixill** [alis0nc/bendyboi-tracker#9]
```
[15:59] BOTBendybot: Bus 23318 is now offline.
12 July 2018
[16:51] Withonel: !whereis 23337
[16:51] BOTBendybot: Bus 23337 is on 275 SOUTHBOUND TELEGRAPH EXP to TAYLOR. Next stop TELEGRAPH + MENOMINEE (ID 22927) at 20180712 16:52
[16:52] Withonel: Put your stamp on the world! go.cmich.edu
[16:53] ShadowFoxNixill: .w.
[16:53] ShadowFoxNixill: !whereis 3002
[16:53] BOTBendybot: Bus 3002 is currently offline.
[16:53] ShadowFoxNixill: !whereis 23318
[16:53] BOTBendybot: Bus 23318 is on 450 NORTHBOUND WOODWARD to PONTIAC. Next stop WOODWARD + BALTIMORE MILWAUKEE (ID 22176) at 20180712 16:54
```
^ An unaltered chatlog from today (first message is on 10 July 2018)

**Comment by alis0nc** [comment]
```
09:01:17: Running tracker
09:06:19: Running tracker
Task exception was never retrieved
future: <Task finished coro=<trackBuses() done, defined at ./app.py:98> exception=AttributeError("'NoneType' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "./app.py", line 103, in trackBuses
    tracker.run()
  File "./app.py", line 71, in run
    r = r.get('bustime-response', None)
AttributeError: 'NoneType' object has no attribute 'get'
```
Borked yesterday

**Comment by alis0nc** [comment]
```
17:08:53: Running tracker                                                       Task exception was never retrieved
future: <Task finished coro=<trackBuses() done, defined at ./app.py:98> exceptio
n=KeyError(0,)>                                                                 Traceback (most recent call last):
  File "./app.py", line 103, in trackBuses
    tracker.run()
  File "./app.py", line 79, in run
    firstPrediction = r['prd'][0]
KeyError: 0

```

**Comment by alis0nc** [comment]
I've added a print statement to the offending function to find out what data SMART is giving us that's causing bendybot to choke. This happens sporadically at best... it's a waiting game now.

**Comment by alis0nc** [comment]
```json
{'prd': {'tmstmp': '20180913 14:23', 'typ': 'D', 'stpnm': 'NORTH RIVER PARK AND RIDE LOT', 'stpid': '23764', 'vid': '3707', 'dstp': '108', 'rt': '561', 'rtdir': 'SOUTHBOUND', 'des': 'FAST GRATIOT TO DETROIT', 'prdtm': '20180913 14:51', 'tablockid': '85620561', 'tatripid': '597849', 'zone': None}}
``` 
Looks like it returns a single element rather than an array when there is only one prediction. Aren't undocumented, inconsistent APIs just wonderful?
